name: Build and test PHP MapScript

on:
  push:
    branches:
      - '*'
    except:
      - /^(cherry-pick-)?backport-\d+-to-/

jobs:
  build:
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        php-version: [8.1, 8.2]
    env:
      RUN_MSAUTOTESTS: 'true'

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Uninstall PHP
        run: |
          sudo apt-get purge '^php.*' -y

      - name: Setup PHP
        run: |
          sudo add-apt-repository ppa:ondrej/php -y
          sudo apt-get install -y --no-install-recommends \
          php${{ matrix.php-version }}-dev php${{ matrix.php-version }}-xml php${{ matrix.php-version }}-mbstring

      # - name: Set up PHP ${{ matrix.php-version }}
      #   uses: shivammathur/setup-php@v2
      #   with:
      #     php-version: ${{ matrix.php-version }}
      #     extensions: none, xml, mbstring

      - name: Install dependencies
        run: ./ci/setup.sh

      - name: Build
        run: ./ci/build.sh
