# check for Windows CRLF in files
# homepage: https://github.com/marketplace/actions/check-crlf

name: Check CRLF

on: [push, pull_request]

jobs:
  Check-CRLF:
    name: verify that only LF linefeeds are used
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository contents
        uses: actions/checkout@v3

      - name: Use action to check for CRLF endings
        uses: erclu/check-crlf@v1.2.0
        with: # ignore directories containing *.pdf and *.tab
          exclude: msautotest/misc/data/ /msautotest/renderers/expected/